site_name: Lapidary runtime
repo_url: https://github.com/python-lapidary/lapidary

docs_dir: ../docs

nav:
- index.md
- Usage:
  - usage/client.md
  - usage/operation.md
  - usage/auth.md
- Reference:
  - reference/lapidary.md
