[tools]
poetry = "2.4"
pre-commit = "4.4"
ruff = "0.15"

[tasks]
check = 'ruff check --fix'
format = 'ruff format'
install = 'poetry install --all-groups --all-extras'
mkdocs = 'poetry run mkdocs build -f .config/mkdocs.yaml'
mkdocs-serve = 'poetry run mkdocs serve -f .config/mkdocs.yaml -a 0.0.0.0:8000 --livereload'
