name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - develop  # Set this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # Set this to the Python version you're using

    - name: Install dependencies
      run: |
        pip install mkdocs-material 'mkdocstrings[python]'

    - name: Build site
      run: mkdocs build -f config/mkdocs.yml

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site  # Set this to your 'site_dir' if you have a custom build directory
        cname: lapidary.dev
